# Generated by Django 3.0.6 on 2020-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='fb_profile_link',
            field=models.URLField(default='https://facebook.com/'),
        ),
    ]
