# Generated by Django 3.0.6 on 2020-05-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200518_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parent_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Post')),
            ],
        ),
    ]
